
--CREO UNA FUNZIONE CHE TROVI INDICE DI UN ELEMENTO ALL'INTERNO DI UN ARRAY
--ALL'INTERNO DELLA FUNZIONE CI SARA UN CICLO CHE CONTROLLERA UNO A UNO GLI ELEMENTI ALL'INTERNO DI UN ARRAY 
-- QUANDO L'ELEMENTO ALL'INTERNO DELL ARRAY VIENE TROVATO ALLORA RETURN SARA UGUALE ALL'INDICE DELL'ELEMENTO
SE NELL'ARRAY NON ESISTE QUELL'ELEMENTO ALLORA RETURN = -1
